#!/bin/bash

declare -r threads='16'

ucurl() {
    curl -L -g -s --user-agent 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.15.2 Chrome/87.0.4280.144 Safari/537.36' -H 'Accept-Encoding: gzip, deflate' --compressed "$@"
}

declare -r arg0="$(basename "$0")"

usage() {
    printf '%s [dir] [URL]...\nArchive xnxx videos metadata in json to DIR\nUrls are taken from recursive spider starting from URL.\n' "$arg0"
}

get_page() {
    local -r rh="$(sha256sum <<< "$1")"
    local -r name="${rh%  *}"
    [ -e "$name" ] && return
    local -r t="$(ucurl "$1")"
    local jn="$(sed -n '/^<script>if(!window\.xv){window\.xv={};}window\.xv\.conf=/{s/^<script>if(!window\.xv){window\.xv={};}window.xv\.conf=//; s/;<\/script>$//; p;q}' <<< "$t")"
    local _tmp1
    {
    echo "$1" #link
    echo "$(jq -r '.dyn | "\(.id)\n\(.pagefilter)\n\(.vmdata.pub_comments)\n\(.video_title)"' <<< "$jn")" #id #pagefilter #comment_count $title
    jn="$(reliq 'script +type="application/ld+json" | "%i\n"' <<< "$t")"
    echo "$(jq -r '"\(.uploadDate)\n\(.duration)"' <<< "$jn")" #date #duration
    echo "$(sed -n '/^[[:space:]]*html5player.setThumbUrl169(/{s/^.*('\''//; s/'\''.*$//;p;q}' <<< "$t")" #thumbnail
    echo "$(sed -n '/^[[:space:]]*html5player.setThumbSlideBig(/{s/^.*('\''//; s/'\''.*$//;p;q}' <<< "$t")" #mozaique
    _tmp1="$(reliq 'span class="metadata" | "%i\n"' <<< "$t")"
    echo "$(sed -n '/[1-9][0-9]*p[^-]*-[^1-9][1-9][0-9,]*/{s/^- //; s/.*- //; s/ .*//; s/,//g;p}' <<< "$_tmp1")" #views
    echo "$(grep -o '[1-9][0-9]*p' <<< "$_tmp1")" #quality
    reliq '
        . div class="clear-infobar"; a href class="gold-plate" | "%(href)v\n" / sed "s#.*/##" echo "" "\n",
        . span class="rating-box value" | "%i\n" / sed "s/%//",
        . a .vote-action-good; span .value | "%i\n" / tr ",",
        . a .vote-action-bad; span .value | "%i\n" / tr ",",
        . p class="metadata-row video-description" | "%i " / echo "" "\n",
        . div class="metadata-row video-tags"; a href .is-keyword | "%i\t" / echo "" "\n",
        . div class="metadata-row video-tags"; a href .is-pornstar | "%i\t" / echo "" "\n"
    ' <<< "$t"
    } | jq -RnMc '
        .["link"]=input |
        .["id"]=input |
        .["pagefilter"]=input |
        .["comment_count"]=input |
        .["title"]=input |
        .["date"]=input |
        .["duration"]=input |
        .["thumbnail"]=input |
        .["mozaique"]=input |
        .["views"]=input |
        .["quality"]=input |
        .["goldplate"]=input |
        .["rating"]=input |
        .["likes"]=input |
        .["dlikes"]=input |
        .["desc"]=input |
        .["tags"]=(input | split("\t"))[:-1] |
        .["stars"]=(input | split("\t"))[:-1]' > "$name"
    sed -n '/^<script>var video_related=/{s/^<script>var video_related=//; s/];window\..*/]/; p}' <<< "$t" | jq -r '"https://www.xnxx.com\(.[].u)"'
}

if [ "$#" -lt '2' ]
then
    usage >&2
    exit 1
fi

cd "$1" || exit 1
shift

t1="$(mktemp)"
trap 'rm "$t1"' EXIT
while [ "$#" -gt 0 ]
do
    echo "$1" >&2
    get_page "$1"
    shift
done > "$t1"

while :
do
    [ -s "$t1" ] || exit
    j="$(sort -u "$t1")"
    for i in $j
    do
        [ "$(jobs | wc -l)" -gt "$threads" ] && wait %%
        echo "$i" >&2
        get_page "$i" &
    done > "$t1"
    wait
done
